server.port=8081

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

# En Docker Compose existe la env AUTH_SERVER_URL=http://authorization-server:9000
# En local, si no existe, cae a http://localhost:9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_URL:http://localhost:9000}

# La DB ya se inyecta por docker-compose con:
# SPRING_DATASOURCE_URL / USERNAME / PASSWORD
# (Spring Boot las lee automáticamente)
# Si ejecutas fuera de Docker, esto te sirve como fallback:
spring.datasource.url=jdbc:mysql://localhost:3306/aghairsalon?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# ------------------------------
# OKR5: Observabilidad (Actuator)
# ------------------------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Útil para latencias p95/p99 en Grafana (cuando montemos Prometheus/Grafana)
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=resource-server
