name: security-secrets

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  secret-scan:
    name: TruffleHog secret scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          # Esto evita ruido y te saca verified + unknown
          # Si quieres que BLOQUEE el merge cuando encuentre algo, deja --fail.
          extra_args: --results=verified,unknown --fail
